### ISSUE TITLE
Setting the number of threads for parallel approximate DBSCAN clustering

### ISSUE THREAD

**Issue by amir-keramatian** [wangyiqiu/dbscan#2]
The approximate DBSCAN seems to utilize only 1 thread. I tried to set the number of threads via the environment variable PARLAY_NUM_THREADS, but it does not seem to make any difference. Can you please instruct me how to set the number of threads?

Furthermore, with small values of Rho, I sometimes get the following error: Command terminated by signal 11
Do you have a fix for it? Thank you.

**Comment by wangyiqiu** [comment]
Our code back then requires CILK to run in parallel, but CILK is deprecated in the newest GCC. For our [paper ](https://arxiv.org/pdf/1912.06255.pdf) we were using GCC 7.4. What version of GCC were you using?

If you hope to adjust the thread count for CILK, you could set environment variable "CILK_NWORKERS", rather than "PARLAY_NUM_THREADS".

**Comment by amir-keramatian** [comment]
Thank you for your answer. 

Lack of CILK was indeed the source of problem. I tried the project on Ubuntu 18.04, and now it works. 

Furthermore, I am now able to adjust the number of threads by CILK_NWORKERS. Thank you.
